import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { toast } from "sonner";
import { UserRound, ArrowLeft, ArrowRight, Save, Loader2 } from "lucide-react";
import FounderProgress from "@/components/FounderProgress";
import { API, useApp } from "@/context/AppContext";
import { Page, Hero, Card, Btn, FieldLabel, Input, Textarea } from "@/components/bm";

const OPEN = "noch offen";
const EMPTY = { founder_path: "", interests: "", skills_experience: "", enjoyable_activities: "", preferred_work_style: OPEN, preferred_work_location: OPEN, desired_customer_group: OPEN, available_time: OPEN, start_budget: OPEN, desired_speed: OPEN, constraints: "", excluded_industries: "", rough_topic: "", rough_thoughts: "", idea_working_title: "", idea_description: "", planned_offer: "", assumed_target_group: "", planned_revenue_source: "" };
const options = { preferred_work_style: ["allein", "kleines Team", "später größeres Unternehmen", OPEN], preferred_work_location: ["online", "lokal", "hybrid", OPEN], desired_customer_group: ["Privatkunden", "Unternehmen", "beides", OPEN], available_time: ["nebenberuflich wenige Stunden", "nebenberuflich regelmäßig", "Vollzeit", OPEN], start_budget: ["nahezu kein Budget", "bis 1.000 Euro", "1.000 bis 5.000 Euro", "über 5.000 Euro", OPEN], desired_speed: ["möglichst schnell erste Einnahmen", "nachhaltiger Aufbau", "skalierbares Unternehmen", OPEN] };
function Select({ name, value, onChange }) { return <select className="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-zinc-100 focus:outline-none focus:ring-2 focus:ring-violet-400" value={value || OPEN} onChange={(e) => onChange(name, e.target.value)}>{options[name].map((o) => <option key={o}>{o}</option>)}</select>; }

export default function FounderProfile() {
  const navigate = useNavigate(); const { language } = useApp();
  const [form, setForm] = useState(EMPTY); const [step, setStep] = useState(0); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const isEN = language === "EN";
  useEffect(() => { let alive = true; (async () => { try { const { data } = await axios.get(`${API}/founder/profile`); if (alive) setForm({ ...EMPTY, ...data }); } catch { toast.error("Gründerprofil konnte nicht geladen werden"); } finally { if (alive) setLoading(false); } })(); return () => { alive = false; }; }, []);
  const set = (k, v) => setForm((p) => ({ ...p, [k]: v.slice ? v.slice(0, 1200) : v }));
  const save = async (nextRoute = "") => { setSaving(true); try { await axios.put(`${API}/founder/profile`, form); await axios.put(`${API}/onboarding/status`, { status: "in_progress", selected_path: "founder", current_step: "profile" }); toast.success(isEN ? "Founder profile saved" : "Gründerprofil gespeichert"); if (nextRoute) navigate(nextRoute); } catch { toast.error("Speichern fehlgeschlagen"); } finally { setSaving(false); } };
  const total = useMemo(() => form.founder_path === "concrete_idea" ? 3 : 3, [form.founder_path]);
  const next = () => step < total - 1 ? setStep(step + 1) : save(form.founder_path === "concrete_idea" ? "/onboarding/founder/ideas" : "/onboarding/founder/ideas");
  return <Page><FounderProgress current="profile" /><Hero icon={UserRound} badge="Gründungs-KI-Experte" title={isEN ? "Founder profile" : "Gründerprofil"} description={isEN ? "Step by step, without judgement or sensitive details." : "Schrittweise, ohne Bewertung und ohne Pflicht zu sensiblen Details."} actions={<><Btn variant="ghost" onClick={() => navigate('/onboarding/founder/start')}><ArrowLeft size={14}/>Zurück</Btn><Btn onClick={next} disabled={saving}>{saving ? <Loader2 size={14} className="animate-spin"/> : <ArrowRight size={14}/>}Weiter</Btn></>} />
  <Card>{loading ? <Loader2 className="animate-spin"/> : <div className="grid gap-4 md:grid-cols-2">
    {step === 0 && <><div><FieldLabel>Interessen und Themen</FieldLabel><Textarea value={form.interests} onChange={(e)=>set('interests',e.target.value)} /></div><div><FieldLabel>Fähigkeiten und berufliche Erfahrungen</FieldLabel><Textarea value={form.skills_experience} onChange={(e)=>set('skills_experience',e.target.value)} /></div><div className="md:col-span-2"><FieldLabel>Tätigkeiten, die du gerne ausübst</FieldLabel><Textarea value={form.enjoyable_activities} onChange={(e)=>set('enjoyable_activities',e.target.value)} /></div></>}
    {step === 1 && Object.keys(options).map((k) => <div key={k}><FieldLabel>{k.replaceAll('_',' ')}</FieldLabel><Select name={k} value={form[k]} onChange={set}/></div>)}
    {step === 2 && <><div><FieldLabel>Persönliche Rahmenbedingungen (optional)</FieldLabel><Textarea value={form.constraints} onChange={(e)=>set('constraints',e.target.value)} /></div><div><FieldLabel>Ausgeschlossene Tätigkeiten oder Branchen (optional)</FieldLabel><Textarea value={form.excluded_industries} onChange={(e)=>set('excluded_industries',e.target.value)} /></div>{form.founder_path === 'rough_direction' && <><div><FieldLabel>Thema oder Branche</FieldLabel><Input value={form.rough_topic} onChange={(e)=>set('rough_topic',e.target.value)} /></div><div><FieldLabel>Bisherige Gedanken</FieldLabel><Textarea value={form.rough_thoughts} onChange={(e)=>set('rough_thoughts',e.target.value)} /></div></>}{form.founder_path === 'concrete_idea' && <><div><FieldLabel>Arbeitstitel der Idee</FieldLabel><Input value={form.idea_working_title} onChange={(e)=>set('idea_working_title',e.target.value)} /></div><div><FieldLabel>Kurze Beschreibung</FieldLabel><Textarea value={form.idea_description} onChange={(e)=>set('idea_description',e.target.value)} /></div><div><FieldLabel>Geplantes Produkt oder Dienstleistung</FieldLabel><Input value={form.planned_offer} onChange={(e)=>set('planned_offer',e.target.value)} /></div><div><FieldLabel>Vermutete Zielgruppe</FieldLabel><Input value={form.assumed_target_group} onChange={(e)=>set('assumed_target_group',e.target.value)} /></div><div><FieldLabel>Geplante Einnahmequelle</FieldLabel><Input value={form.planned_revenue_source} onChange={(e)=>set('planned_revenue_source',e.target.value)} /></div></>}</>}
    <div className="md:col-span-2 flex flex-wrap gap-3"><Btn variant="ghost" disabled={step===0} onClick={()=>setStep(step-1)}>Zurück</Btn><Btn variant="ghost" onClick={()=>save()} disabled={saving}><Save size={14}/>Speichern und später fortsetzen</Btn></div>
  </div>}</Card></Page>;
}
