import React, { useState } from "react";
import axios from "axios";
import { Globe, Loader2, Check, X, ShieldCheck, AlertTriangle, ExternalLink, Trash2 } from "lucide-react";
import { PageHeader } from "@/components/PageHeader";
import { API, useApp } from "@/context/AppContext";

const labels = {
  brand_name: ["Markenname", "Brand name"], industry: ["Branche", "Industry"], website: ["Website", "Website"],
  short_description: ["Kurzbeschreibung", "Short description"], products_services: ["Produkte & Leistungen", "Products & services"],
  target_audience: ["Zielgruppe", "Target audience"], customer_needs: ["Kundenprobleme / Bedürfnisse", "Customer needs"],
  value_proposition: ["Nutzenversprechen", "Value proposition"], positioning: ["Positionierung", "Positioning"],
  differentiators: ["Differenzierungsmerkmale", "Differentiators"], brand_values: ["Markenwerte", "Brand values"],
  tone: ["Tonalität", "Tone"], keywords: ["Häufige Schlüsselbegriffe", "Frequent keywords"], primary_colors: ["Hauptfarben", "Main colors"],
  logo_candidate: ["Logo-Kandidat", "Logo candidate"], visual_style: ["Visuelle Stilrichtung", "Visual style"],
  social_links: ["Social-Media-Links", "Social media links"], contact_info: ["Kontaktinformationen", "Contact information"],
};
const text = (v) => Array.isArray(v) ? v.join(", ") : (v || "");

export default function WebsiteBrandImport() {
  const { lang, activeBrand, loadBrands, updateOnboardingStatus } = useApp();
  const de = lang === "DE"; const T = (a,b) => de ? a : b;
  const [url,setUrl]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const [draft,setDraft]=useState(null); const [selected,setSelected]=useState({}); const [edited,setEdited]=useState({}); const [confirm,setConfirm]=useState(null);
  const analyze=async()=>{ setLoading(true); setError(""); setDraft(null); try { const res=await axios.post(`${API}/brand-imports/website`,{url, brand_id: activeBrand?.id}); setDraft(res.data); const high={}; Object.entries(res.data.extracted_fields||{}).forEach(([k,f])=>{ if(f?.value && f.confidence==="high") high[k]=true; }); setSelected(high); } catch(e){ setError(e?.response?.data?.detail || T("Website konnte nicht analysiert werden. Du kannst eine andere URL versuchen oder manuell fortfahren.","Website could not be analyzed. You can try another URL or continue manually.")); } finally { setLoading(false); } };
  const manual=async()=>{ await updateOnboardingStatus?.({selected_path:"existing_brand", current_step:"brand_brain", status:"in_progress"}).catch(()=>{}); window.location.href="/brand-brain"; };
  const discard=async()=>{ if(draft?.id) await axios.delete(`${API}/brand-imports/${draft.id}`).catch(()=>{}); setDraft(null); setConfirm(null); };
  const confirmSelected=async()=>{ const payload={}; Object.entries(selected).forEach(([k,on])=>{ if(on) payload[k]={value: edited[k] ?? draft.extracted_fields[k]?.value}; }); const res=await axios.post(`${API}/brand-imports/${draft.id}/confirm`,{selected_fields:payload, conflict_resolutions:{}}); setConfirm(res.data); await loadBrands(); };
  const fields=Object.entries(draft?.extracted_fields||{});
  return <div className="max-w-5xl mx-auto">
    <PageHeader icon={Globe} color="#7C3AED" badge={T("Existing Brand · Website Import","Existing Brand · Website import")} title={T("Lass Brandmind deine Marke kennenlernen","Let Brandmind get to know your brand")} subtitle={T("Gib die Adresse deiner Website ein. Brandmind analysiert öffentlich zugängliche Inhalte und erstellt daraus einen Markenprofil-Entwurf, den du vor dem Speichern prüfen und bearbeiten kannst.","Enter your website address. Brandmind analyzes publicly available content and creates an editable brand profile draft for you to review before saving.")} />
    <div className="rounded-sm border border-white/10 bg-[#0A0A0A] p-5 mb-5">
      <label className="block text-[11px] uppercase tracking-[0.15em] text-zinc-500 mb-2">{T("Website-URL","Website URL")}</label>
      <div className="flex flex-col sm:flex-row gap-3"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com" className="flex-1 bg-black/40 border border-white/10 rounded-sm px-3 py-2.5 text-sm text-white placeholder:text-zinc-600 focus:outline-none focus:border-[#7C3AED]/50" />
      <button onClick={analyze} disabled={loading||!url.trim()} className="px-5 py-2.5 rounded-sm bg-[#7C3AED] text-white text-sm font-semibold disabled:opacity-50 inline-flex items-center gap-2">{loading && <Loader2 className="animate-spin" size={16}/>} {T("Website analysieren","Analyze website")}</button>
      <button onClick={manual} className="px-5 py-2.5 rounded-sm border border-white/15 text-white text-sm">{T("Ohne Website manuell einrichten","Set up manually without website")}</button></div>
      {error && <div className="mt-4 rounded-sm border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200"><AlertTriangle size={16} className="inline mr-2"/>{error}<div className="mt-3 flex gap-2 flex-wrap"><button onClick={()=>setError("")} className="underline">{T("Andere Website versuchen","Try another website")}</button><button onClick={manual} className="underline">{T("Fehlende Angaben manuell ergänzen","Add missing details manually")}</button></div></div>}
    </div>
    {draft && <div className="space-y-5">
      <div className="rounded-sm border border-emerald-500/25 bg-emerald-500/10 p-4"><ShieldCheck className="inline mr-2" size={18}/><b>{T("Wir haben Informationen zu deiner Marke gefunden.","We found information about your brand.")}</b><p className="text-sm text-zinc-300 mt-1">{T("Bitte prüfe die Vorschläge. Erst nach deiner Bestätigung werden sie als Markenbasis gespeichert.","Please review the suggestions. They are saved as brand foundation only after your confirmation.")}</p></div>
      <div className="grid md:grid-cols-2 gap-4"><section className="rounded-sm border border-white/10 bg-black/30 p-4"><h3 className="text-sm font-semibold mb-3">{T("Analysierte Seiten","Analyzed pages")}</h3>{(draft.analyzed_pages||[]).map(p=><a key={p.url} className="block text-xs text-zinc-300 hover:text-white mb-2" href={p.url} target="_blank" rel="noreferrer"><ExternalLink size={12} className="inline mr-1"/>{p.title||p.url}</a>)}</section><section className="rounded-sm border border-white/10 bg-black/30 p-4"><h3 className="text-sm font-semibold mb-3">{T("Warnungen / nicht gefundene Bereiche","Warnings / missing areas")}</h3>{(draft.warnings||[]).length?draft.warnings.map(w=><p className="text-xs text-amber-200 mb-2" key={w}>{w}</p>):<p className="text-xs text-zinc-500">{T("Keine kritischen Warnungen.","No critical warnings.")}</p>}</section></div>
      <div className="flex flex-wrap gap-3"><button onClick={()=>{const h={}; fields.forEach(([k,f])=>{if(f.value&&f.confidence==="high")h[k]=true}); setSelected(h)}} className="px-4 py-2 rounded-sm border border-white/15 text-sm">{T("Alle sicheren Angaben auswählen","Select all safe fields")}</button><button onClick={confirmSelected} className="px-4 py-2 rounded-sm bg-[#7C3AED] text-white text-sm">{T("Ausgewählte Angaben übernehmen","Confirm selected fields")}</button><button onClick={manual} className="px-4 py-2 rounded-sm border border-white/15 text-sm">{T("Fehlende Angaben manuell ergänzen","Add missing details manually")}</button><button onClick={discard} className="px-4 py-2 rounded-sm border border-red-500/30 text-red-200 text-sm inline-flex gap-2"><Trash2 size={14}/>{T("Entwurf verwerfen","Discard draft")}</button></div>
      <div className="grid gap-3">{fields.map(([k,f])=> <div key={k} className="rounded-sm border border-white/10 bg-[#0A0A0A] p-4"><div className="flex items-start justify-between gap-3"><div><h4 className="font-semibold">{(labels[k]||[k,k])[de?0:1]}</h4><p className="text-[11px] uppercase tracking-wider text-zinc-500">{f.confidence} · {f.extraction_type === "explicit" ? T("explizit gefunden","explicitly found") : T("abgeleitet","inferred")}</p></div><label className="text-sm text-zinc-300"><input type="checkbox" className="mr-2" checked={!!selected[k]} onChange={e=>setSelected(s=>({...s,[k]:e.target.checked}))}/>{T("Übernehmen","Use")}</label></div><textarea value={edited[k] ?? text(f.value)} onChange={e=>setEdited(x=>({...x,[k]:e.target.value}))} className="mt-3 w-full min-h-[74px] bg-black/40 border border-white/10 rounded-sm px-3 py-2 text-sm text-white" placeholder={T("Nicht gefunden","Not found")}/><p className="mt-2 text-xs text-zinc-400">{f.evidence_summary}</p><div className="mt-2 flex flex-wrap gap-2">{(f.source_urls||[]).map(u=><span key={u} className="text-[11px] text-zinc-500 border border-white/10 px-2 py-1 rounded-sm truncate max-w-xs">{u}</span>)}</div><button onClick={()=>setSelected(s=>({...s,[k]:false}))} className="mt-2 text-xs text-zinc-500 hover:text-white inline-flex gap-1"><X size={12}/>{T("Ablehnen / nicht verwenden","Reject / do not use")}</button></div>)}</div>
    </div>}
    {confirm && <div className="mt-5 rounded-sm border border-white/10 bg-black/30 p-4"><Check className="inline mr-2 text-emerald-400" size={18}/>{T("Bestätigung gespeichert. Aktualisierte Felder:","Confirmation saved. Updated fields:")} {(confirm.updated_fields||[]).join(", ") || "—"}{(confirm.conflicts||[]).length>0 && <p className="text-amber-200 text-sm mt-2">{T("Konflikte wurden nicht überschrieben. Bitte im manuellen Formular entscheiden.","Conflicts were not overwritten. Please decide in the manual form.")}</p>}</div>}
  </div>;
}
