export const NAV_GROUPS = [
  { id: "home", labelDE: "Home", labelEN: "Home", to: "/app", icon: "Building2", primary: true, items: [{ to: "/app", labelDE: "BrandMind HQ", labelEN: "BrandMind HQ", end: true }] },
  { id: "quantum", labelDE: "Quantum", labelEN: "Quantum", to: "/quantum", icon: "Crown", primary: true, highlight: true, items: [{ to: "/quantum", labelDE: "Quantum Command", labelEN: "Quantum Command" }] },
  { id: "journey", labelDE: "Gründung", labelEN: "Founder Journey", icon: "TrendingUp", items: [
    { to: "/onboarding/select-path", labelDE: "Einstieg & Pfadwahl", labelEN: "Start & path select" }, { to: "/onboarding/founder/ideas", labelDE: "Ideen", labelEN: "Ideas" }, { to: "/onboarding/founder/ideas/compare", labelDE: "Ideen-Vergleich", labelEN: "Idea compare" }, { to: "/onboarding/founder/business-plan", labelDE: "Businessplan", labelEN: "Business plan" }, { to: "/onboarding/founder/finance", labelDE: "Finanzplan", labelEN: "Finance plan" }, { to: "/onboarding/founder/offers", labelDE: "Angebote", labelEN: "Offers" },
  ]},
  { id: "my-brand", labelDE: "Meine Marke", labelEN: "My Brand", icon: "BrainCircuit", items: [
    { to: "/brand-brain", labelDE: "Brand Brain", labelEN: "Brand Brain" }, { to: "/brand-identity", labelDE: "Brand Identity", labelEN: "Brand Identity" }, { to: "/knowledge", labelDE: "Knowledge Base", labelEN: "Knowledge Base" }, { to: "/knowledge-graph", labelDE: "Knowledge Graph", labelEN: "Knowledge Graph" }, { to: "/memory", labelDE: "Memory", labelEN: "Memory" },
  ]},
  { id: "create", labelDE: "Erstellen", labelEN: "Create", icon: "Palette", items: [
    { to: "/social", labelDE: "Social Media", labelEN: "Social Media" }, { to: "/design", labelDE: "Design Studio", labelEN: "Design Studio" }, { to: "/video", labelDE: "Video Studio", labelEN: "Video Studio" }, { to: "/seo", labelDE: "SEO", labelEN: "SEO" }, { to: "/email", labelDE: "Email", labelEN: "Email" }, { to: "/linkedin", labelDE: "LinkedIn", labelEN: "LinkedIn" }, { to: "/tiktok", labelDE: "TikTok", labelEN: "TikTok" }, { to: "/tts", labelDE: "TTS", labelEN: "TTS" }, { to: "/output-factory", labelDE: "Output Factory", labelEN: "Output Factory" },
  ]},
  { id: "projects", labelDE: "Projekte", labelEN: "Projects", icon: "Target", items: [
    { to: "/mission", labelDE: "Mission Control", labelEN: "Mission Control" }, { to: "/campaign", labelDE: "Campaign", labelEN: "Campaign" }, { to: "/workflow", labelDE: "Campaign Flow", labelEN: "Campaign Flow" }, { to: "/automation", labelDE: "Automation", labelEN: "Automation" }, { to: "/workflow-architect", labelDE: "Workflow Architect", labelEN: "Workflow Architect" }, { to: "/orchestrator", labelDE: "Orchestrator", labelEN: "Orchestrator" }, { to: "/ops", labelDE: "Content Ops", labelEN: "Content Ops" }, { to: "/tickets", labelDE: "Tickets", labelEN: "Tickets" },
  ]},
  { id: "more", labelDE: "Mehr", labelEN: "More", icon: "LayoutGrid", items: [
    { to: "/agents", labelDE: "Agents", labelEN: "Agents" }, { to: "/builder", labelDE: "Custom Agents", labelEN: "Custom Agents" }, { to: "/character-studio", labelDE: "Character Studio", labelEN: "Character Studio" }, { to: "/ai-business-card", labelDE: "AI Business Card", labelEN: "AI Business Card" }, { to: "/intelligence", labelDE: "Intelligence", labelEN: "Intelligence" }, { to: "/analytics", labelDE: "Analytics", labelEN: "Analytics" }, { to: "/skills", labelDE: "Skills", labelEN: "Skills" }, { to: "/modules", labelDE: "Marketplace", labelEN: "Marketplace" }, { to: "/arena", labelDE: "Chat Arena", labelEN: "Chat Arena" }, { to: "/gateway", labelDE: "Gateway", labelEN: "Gateway" }, { to: "/billing", labelDE: "Plans", labelEN: "Plans" }, { to: "/permissions", labelDE: "Permissions", labelEN: "Permissions" },
  ], subgroups: [{ id: "business-finance", labelDE: "Business & Finanzen", labelEN: "Business & Finance", items: [
    { to: "/finance-cfo", labelDE: "CFO Studio", labelEN: "CFO Studio" }, { to: "/finance-analyst", labelDE: "Financial Analyst", labelEN: "Financial Analyst" }, { to: "/finance-fpa", labelDE: "FP&A Studio", labelEN: "FP&A Studio" }, { to: "/finance-bookkeeper", labelDE: "Bookkeeper", labelEN: "Bookkeeper" }, { to: "/finance-tax", labelDE: "Tax Studio", labelEN: "Tax Studio" },
  ]}]},
];
export const NAV = NAV_GROUPS.flatMap((g) => [...(g.items || []), ...(g.subgroups || []).flatMap((s) => s.items || [])]);
export const CENTRAL_APP_ROUTES = ["/app","/quantum","/brand-brain","/brand-identity","/knowledge","/knowledge-graph","/memory","/social","/design","/video","/seo","/email","/linkedin","/tiktok","/tts","/output-factory","/mission","/campaign","/workflow","/automation","/workflow-architect","/orchestrator","/ops","/tickets","/finance-cfo","/finance-analyst","/finance-fpa","/finance-bookkeeper","/finance-tax"];
